name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.3
          version: 1

      - name: Run PHPUnit
        run: php7.3 vendor/bin/phpunit
