name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.3
          version: 1

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.3
          memory_limit: 256M
